# Generated by Django 4.2.2 on 2023-07-30 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=50)),
                ('ProductDescription', models.CharField(max_length=200)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Data', models.DateTimeField(auto_now_add=True)),
                ('print_print', models.CharField(choices=[('Name', 'name'), ('Description', 'description'), ('Price', 'price'), ('Data', 'data')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreName', models.CharField(max_length=50)),
                ('StoreAddress', models.CharField(max_length=100)),
                ('StoreContact', models.CharField(max_length=100)),
                ('StoreDescription', models.TextField()),
                ('StoreWorkingHours', models.TimeField()),
                ('StoreEmail', models.EmailField(max_length=254)),
                ('StoreWebsite', models.URLField()),
                ('print_print', models.CharField(choices=[('Name', 'name'), ('Address', 'address'), ('Contact', 'contact'), ('Description', 'description'), ('Working Hours', 'Working hours'), ('Email', 'email'), ('Website', 'website')], max_length=100)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
