# Generated by Django 4.2.2 on 2023-08-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Data',
            new_name='Date',
        ),
        migrations.RemoveField(
            model_name='people',
            name='Username',
        ),
        migrations.RemoveField(
            model_name='store',
            name='StoreEmail',
        ),
        migrations.RemoveField(
            model_name='store',
            name='StoreWebsite',
        ),
        migrations.RemoveField(
            model_name='store',
            name='StoreWorkingHours',
        ),
        migrations.AddField(
            model_name='people',
            name='File',
            field=models.FileField(default='default_file.png', upload_to='templates/main'),
        ),
        migrations.AddField(
            model_name='people',
            name='Login',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='people',
            name='print_print',
            field=models.CharField(choices=[('Login', 'login'), ('Password', 'password')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ProductCompany',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductDescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='print_print',
            field=models.CharField(choices=[('Name', 'name'), ('Description', 'description'), ('Price', 'price'), ('Date', 'date'), ('Company', 'company')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='print_print',
            field=models.CharField(choices=[('Name', 'name'), ('Address', 'address'), ('Contact', 'contact'), ('Description', 'description')], max_length=100),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreditCardNumber', models.CharField(max_length=16)),
                ('CardholderName', models.CharField(max_length=50)),
                ('ExpirationDate', models.DateField()),
                ('CVV', models.CharField(max_length=4)),
                ('People', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.people')),
            ],
        ),
    ]
