# Generated by Django 4.2.2 on 2023-08-03 17:04

import django.contrib.auth.views
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.edit


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_data_product_date_remove_people_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.people')),
            ],
            bases=('main.people', django.contrib.auth.views.LoginView),
        ),
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.people')),
            ],
            bases=('main.people', django.views.generic.edit.CreateView),
        ),
        migrations.AddField(
            model_name='people',
            name='Address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.address'),
        ),
    ]
