# Generated by Django 4.2.2 on 2023-08-10 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_address_loginuser_registeruser_people_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='Product',
        ),
        migrations.AddField(
            model_name='product',
            name='Store',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='main.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
            preserve_default=False,
        ),
    ]
