# Generated by Django 4.2.2 on 2023-08-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_remove_store_product_product_store_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='Data_joined',
            new_name='Data_birth',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='CVV',
        ),
        migrations.RemoveField(
            model_name='people',
            name='Password',
        ),
    ]
