# Generated by Django 4.2.2 on 2023-08-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_data_joined_people_data_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='print_print',
            field=models.CharField(choices=[('Login', 'login'), ('Email', 'email')], max_length=100),
        ),
    ]
