# Generated by Django 4.2.2 on 2023-08-20 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_people_print_print'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='Data_birth',
            new_name='Date_birth',
        ),
    ]
