# Generated by Django 4.2.2 on 2023-10-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_data_birth_people_date_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='ExpirationDate',
            field=models.DateField(max_length=5),
        ),
    ]
